/*

Copyright (c) 2007 David Lambert

This file is part of Factory.

Factory is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

Factory is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Factory; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

$Source: /cvsroot/projectfactory/development/net/sourceforge/projectfactory/server/actors/Skill.java,v $
$Revision: 1.10 $
$Date: 2007/01/29 22:26:56 $
$Author: ddlamb_2000 $

*/

package net.sourceforge.projectfactory.server.actors;

import net.sourceforge.projectfactory.server.entities.BaseEntity;
import net.sourceforge.projectfactory.server.xml.TransactionXML;
import net.sourceforge.projectfactory.xml.WriterXML;

/** Defines a skill with level.
  * Generated by David Lambert
  * On Monday, January 29, 2007 9:57:57 AM CET
  * Using Factory 0.4.8.4
  */
public class Skill extends BaseEntity {
    public String skill;
    public int level;
    public String comment;

    /** Writes the object as an XML output. */
    public void xmlOut(WriterXML xml, TransactionXML transaction, boolean tags) {
        if (tags) xmlStart(xml, "skill");
        super.xmlOut(xml, transaction, false);
        if (transaction.isDetail() || transaction.isSave()) {
            xmlAttribute(xml, "skill", skill);
            xmlAttribute(xml, "level", level);
            xmlAttribute(xml, "comment", comment);
        }
        if (tags) xmlEnd(xml);
    }

    /** Reads the object from an XML input. */
    public boolean xmlIn(WriterXML xml, TransactionXML transaction, String tag, String value) {
        if (super.xmlIn(xml, transaction, tag, value)) return true;
        if (tag.equals("skill")) {
            skill = value;
            return true;
        }
        if (tag.equals("level")) {
            level = xmlInInt(xml, value);
            return true;
        }
        if (tag.equals("comment")) {
            comment = value;
            return true;
        }
        return false;
    }
}
