/*

Copyright (c) 2007 David Lambert

This file is part of Factory.

Factory is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

Factory is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Factory; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

$Source: /cvsroot/projectfactory/development/net/sourceforge/projectfactory/server/data/ComboBoxItem.java,v $
$Revision: 1.2 $
$Date: 2007/02/08 15:58:59 $
$Author: ddlamb_2000 $

*/

package net.sourceforge.projectfactory.server.data;

import net.sourceforge.projectfactory.server.entities.BaseEntity;
import net.sourceforge.projectfactory.xml.WriterXML;
import net.sourceforge.projectfactory.xml.server.TransactionXML;

/** 
  * Item that defines a combobox.
  * Generated by David Lambert
  * On Thursday, February 8, 2007 1:27:19 PM CET
  * Using Factory 0.4.8.8
  */
public class ComboBoxItem extends BaseEntity {
    public String code;
    public String label;
    public String style;
    public String icon;

    /** Writes the object as an XML output. */
    public void xmlOut(WriterXML xml, TransactionXML transaction, boolean tags) {
        if (tags) xmlStart(xml, "item");
        super.xmlOut(xml, transaction, false);
        if (transaction.isDetail() || transaction.isSave()) {
            xmlAttribute(xml, "code", code);
            xmlAttribute(xml, "label", label);
            xmlAttribute(xml, "style", style);
            xmlAttribute(xml, "icon", icon);
        }
        if (tags) xmlEnd(xml);
    }

    /** Reads the object from an XML input. */
    public boolean xmlIn(WriterXML xml, TransactionXML transaction, String tag, String value) {
        if (super.xmlIn(xml, transaction, tag, value)) return true;
        if (tag.equals("code")) {
            code = value;
            return true;
        }
        if (tag.equals("label")) {
            label = value;
            return true;
        }
        if (tag.equals("style")) {
            style = value;
            return true;
        }
        if (tag.equals("icon")) {
            icon = value;
            return true;
        }
        return false;
    }
}
